#! /bin/bash

# Launch a system tray app
trayer --edge top \
       --align right \
       --SetDockType true \
       --SetPartialStrut true \
       --expand true \
       --width 15 --height 12 \
       --transparent true --tint 0x000000 &

# Bring in some utilities from Mate
mate-screensaver
mate-settings-daemon

if [ -x /usr/bin/mate-power-manager ]; then
  sleep 1
  mate-power-manager
fi
# 
# if [ -x /usr/bin/nm-applet ]; then
#   nm-applet --sm-disable &
# fi

exec /home/victor/.local/bin/xmonad

